openapi: 3.0.0
info:
  title: Furniture Order App API
  version: 1.0.0
  description: API Documentation for Furniture Order App

servers:
  - url: http://localhost:4000/api
    description: Local Server

tags:
  - name: Furniture Categories
    description: Endpoints related to furniture categories
  - name: Furniture Items
    description: Endpoints for managing furniture items

paths:
  /furniture-categories:
    post:
      summary: Create new category
      tags:
        - Furniture Categories
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - categoryName
                - categoryImage
              properties:
                categoryName:
                  type: string
                  example: Chairs
                categoryImage:
                  type: string
                  format: binary
      responses:
        201:
          description: New Category Added Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  message:
                    type: string
                    example: New Category Added Successfully
        400:
          description: Bad request (image missing or category already exists)
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Fail
                  message:
                    type: string
                    example: Image is Required
        500:
          description: Server error while adding category
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Failed to Add Category

    get:
      summary: Get all furniture categories
      tags:
        - Furniture Categories
      responses:
        200:
          description: List of furniture categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  message:
                    type: string
                    example: Fetch All Category Items Successfully
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: 64d9f8a2c1234abcd56789ef
                        categoryName:
                          type: string
                          example: Chairs
                        categoryImage:
                          type: string
                          example: https://example.com/uploads/chairs.png
        404:
          description: No category found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Fail
                  message:
                    type: string
                    example: No category
        500:
          description: Server error while fetching categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Failed to Fetch Category Items

  /items:
    post:
      summary: Add a new furniture item
      tags:
        - Furniture Items
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - itemName
                - itemCategory
                - itemType
                - itemPrice
                - itemColor
                - itemAvailability
                - itemDescription
                - itemImages
                - itemDimension[length]
                - itemDimension[width]
                - itemDimension[height]
                - itemDimension[unit]
              properties:
                itemName:
                  type: string
                  example: "3-Seater Sofa"
                itemCategory:
                  type: string
                  example: "Sofa & Couches"
                itemType:
                  type: string
                  example: "3-Seater"
                itemPrice:
                  type: number
                  example: 25000
                itemDiscount:
                  type: number
                  example: 25000
                itemColor:
                  type: string
                  example: '["Blue","Gray"]'
                itemAvailability:
                  type: string
                  description: 'available, not available'
                  example: "available"
                itemDescription:
                  type: string
                  example: "A cozy 3-seater sofa with premium fabric upholstery and cushioned comfort, perfect for modern living rooms."
                itemWeight:
                  type: string
                  example: "30kg"
                itemMaterial:
                  type: string
                  example: "Leather"
                itemStyle:
                  type: string
                  example: "Modern"
                itemBrand:
                  type: string
                  example: "ComfortLiving"
                itemWarranty:
                  type: string
                  example: "2 years"
                itemAssembly:
                  type: string
                  example: "Assembly required"
                itemCareInstruction:
                  type: string
                  example: "Wipe with a damp cloth"
                itemDelivaryInfo:
                  type: string
                  example: "Delivery in 5-7 days"
                itemreturnPolicy:
                  type: string
                  example: "30 days return"
                itemImages:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: Upload one or more images
                itemDimension[length]:
                  type: number
                  example: 80
                itemDimension[width]:
                  type: number
                  example: 35
                itemDimension[height]:
                  type: number
                  example: 32
                itemDimension[unit]:
                  type: string
                  example: "in"
      responses:
        201:
          description: New Item Added Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  message:
                    type: string
                    example: New Item Added Successfully
        400:
          description: Bad request (image missing or Item already exists)
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Fail
                  message:
                    type: string
                    example: Image is Required
        500:
          description: Server error while adding item
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Failed to Add Item

  /items/{categoryName}:
    get:
      summary: Get items by category name
      tags:
        - Furniture Items
      parameters:
        - in: path
          name: categoryName
          required: true
          schema:
            type: string
          description: The name of the category to fetch items for
      responses:
        200:
          description: List of items for the given category
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Success
                  message:
                    type: string
                    example: Fetch Items By Category Successfully
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: 64d9f8a2c1234abcd56789ef
                        itemName:
                          type: string
                          example: Wooden Chair
                        itemPrice:
                          type: number
                          example: 12000
                        itemDescription:
                          type: string
                          example: Comfortable wooden chair with cushion
                        itemImage:
                          type: string
                          example: https://example.com/uploads/wooden-chair.png
                        categoryName:
                          type: string
                          example: Chairs
        404:
          description: No items found for the given category
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Fail
                  message:
                    type: string
                    example: No items found in this category
        500:
          description: Server error while fetching items
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: Error
                  message:
                    type: string
                    example: Failed to Fetch Items By Category
